language: java
jdk: oraclejdk8
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: sahilg1@andrew.cmu.edu
  password:
    secure: FQRoGDAbNc+oBxwvxXsUhYKJx7AR9fBJiCLGJrdD58Ra/MxPSzR6eqvTRUMv+m5GFnG6up/+HsrNfiXzfdKvveBalicb7ubN+yBDdqSYJUGi0ByACvjOFxZHLdKVVwel5UgntFKSz/pENG/l0ocuzv4iW2IvFkSfv/tv1P4eTuQhGnHQgDtGiobifYXgIOTWL7hbPKmybgSUqLhjhISJo7W9NoOihOQOUfISc1NcayvoHwqXs3sxSOOf/fD4T7IRlbHXWDOabWogGjHoc79CSKmW5k6b7Cspdz6J3jrQMhxmy9L/7GgmuX85blX5mCjRXgpBZ48z4+uERn6ILlZ7xUXZmuy3wleaHMsVHYEicDw4cL28mGXw8X9PqfSOPiSq33fw9R5z0Qkq6EDdH1U1v+vHI355zDw+bGlcnfqrGc0Q0+iGkiyKk+d2x2Ro/oqLzLnjqSEBboBswzeNp4frXWCyfx8k2pBlsmq1SMjUrSwiLZkrqezjLBYYgOWJt91CucTQVbT7iB5b2kTaSn50MALB11LMjTDWhC3U937EMoZksLfKtiPBpb42DgdUXveL69SG7Bj0RNj64jznl7JZFrQT16Dq8F8ugOBgOd/gFqJRvyzY2pLQh/CpUK+NSrER2qYX9EXoLc23JmHaRahsooXpJ0RCWnZTe4bxcK9Bt2w=
  organization: sahilg1-cmu
  space: development
  on:
    repo: sahilg1/Image-Gallery-Application